### ISSUE TITLE
Makefile: do not set gcc to v.5 and add needed LDLIBS

### ISSUE THREAD

**Issue by rdiaz02** [danro9685/HESBCN#1]
I suggest not setting gcc to version 5 in the Makefile (that is very old) and instead writing `CC = gcc`.  As well, I think LDLIBS (at least in some Linux systems) should be `LDLIBS = -lgsl -lm -lgslcblas`.

**Comment by danro9685** [comment]
Dear @rdiaz02,

Thanks for your suggestions! 
Now updated in the branch master.

Thanks, 
Daniele
