### ISSUE TITLE
AND when they should be Single (as they hang from root)

### ISSUE THREAD

**Issue by rdiaz02** [danro9685/HESBCN#2]
Using the attached data set and running as

```
h-esbcn -d input.txt -o output.txt -n 1e+05 -s 8 --reg bic
```
I get this output

```
best poset: 
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0

 accepted: 0, ratio 0
best theta types = 
0,0,0,0
Best Lambdas:
39.2568 0.498529 0.498529 0.0218925 1 

Best epsilon = 6.62536e-166
```

But having the theta types be 0 (AND) does not seem sensible: all four are independently hanging from the root. The R function `import.hesbcn` translates those 0 as ANDs. I've observed this also with other datasets.

The fix is easy: convert any AND into Single if the node hangs directly from root. But I wonder if this is a bug somewhere else.

[input.txt](https://github.com/danro9685/HESBCN/files/8072084/input.txt)

**Comment by danro9685** [comment]
Dear @rdiaz02,

Thank you for pointing this issue to us, I will look into it as soon as possible. 

Thanks! 
Daniele

**Comment by rdiaz02** [comment]
Thanks. And I just noticed that I am doing something silly: using `-n 1e+05 ` is not the same as `-n 100000`. So maybe that is the cause of the problem. Sorry. I'll close for now, and reopen if this happens with sensible settings (though a big warning or error for users doing stupid things would have saved me from myself ;-) ).
